### PR TITLE
Proposed fix for CPANTESTER fail reports.

### PR DESCRIPTION
**Pull request by manwar**
Hi @ivanych 

Please review the PR. It propose fix to the following fail report.

https://www.cpantesters.org/cpan/report/49dd010e-c1ff-11e8-8fb1-ef5133556b3f

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by ivanych** [comment]
Thanks!

But why is this happening? Log::Any::Adapter::Util is part of the Log::Any, and Log::Any is listed as a dependency in the cpanfile...

**Comment by manwar** [comment]
Hi @ivanych 

I see why it is complaining after looking closely the report. The test environment has Log::Any v0.15, which doesn't have Log::Any::Adapter::Util. It was only introduced in Log::Any v1.032.

I have updated the PR accordingly. Please review it again.

Many Thanks.
Best Regards,
Mohammad S Anwar

**Comment by ivanych** [comment]
Я понял, спасибо!

**Comment by ivanych** [comment]
oops:)

I'm understood, thank you!

**Comment by manwar** [comment]
I could only guess, it was Russian ;-)

**Pull request merged**
